project_id = "xaszbqftcsqdpnbaimgb"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.send-complaint-confirmation]
verify_jwt = false

[functions.validate-complaint-image]
verify_jwt = false

[functions.detect-duplicate-complaint]
verify_jwt = false
